name: Migration

on:
  push:
    branches:
      - prisma/*

jobs:
  migration:
    runs-on: ubuntu-latest
    env:
      RDB_URL: ${{ secrets.RDB_URL }}

    steps:
      - name: Migration pre notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,repo,author
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `${process.env.AS_WORKFLOW} at ${process.env.AS_REPO} by ${process.env.AS_AUTHOR}`,
                fields: [{
                  title: 'starting migration...',
                  short: false
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache dependency
        uses: actions/cache@v3
        id: cache
        with:
          # 'node_modules를 캐싱
          path: node_modules
          # yarn.lock의 파일이 바뀔때마다 다시 캐싱
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Extract branch name for Prisma command
        id: extract-branch
        run: |
          PRISMA_COMMAND=${GITHUB_REF#refs/heads/prisma/}
          echo "PRISMA_COMMAND=${PRISMA_COMMAND}" >> $GITHUB_ENV

      - name: Execute Prisma Command Based on Branch Name
        run: |
          npm install -g prisma
          if [[ "$PRISMA_COMMAND" == "force-reset" ]]; then
            npx prisma db push --force-reset
          elif [[ "$PRISMA_COMMAND" == "migrate" ]]; then
            npx prisma migrate deploy
          elif [[ "$PRISMA_COMMAND" == "seed" ]]; then
            npx prisma db seed
          else
            echo "No specific Prisma command for this branch"
          fi

      - name: Migration post notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: job,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_JOB} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
