name: Test

on:
  push:
    branches:
      - test
      - test/*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RDB_URL: ${{ secrets.RDB_URL }}

    steps:
      - name: Test
        run: |
          MIGRATION_COMMAND=${GITHUB_REF#refs/heads/migration/}
          echo "MIGRATION_COMMAND=${MIGRATION_COMMAND}" >> $GITHUB_ENV
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo $MIGRATION_COMMAND
          echo $REPO_NAME
          if [[ "$MIGRATION_COMMAND" == "test-command" ]]; then
            echo "test-command is executed"
          fi
