name: Test

on:
  push:
    branches:
      - test
      - test/*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RDB_URL: ${{ secrets.RDB_URL }}

    steps:
      - name: Test
        run: |
          MIGRATION_COMMAND=${GITHUB_REF#refs/heads/test/}
          echo "MIGRATION_COMMAND=${MIGRATION_COMMAND}" >> $GITHUB_ENV
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo $MIGRATION_COMMAND
          echo $REPO_NAME
          if [[ "$MIGRATION_COMMAND" == "test-command" ]]; then
            echo "test-command is executed"
          fi

      - name: Connect to bastion server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.BASTION_KEY }}
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER_NAME }}
          port: ${{ secrets.BASTION_PORT }}
          script: |
            echo "Connected to bastion server"
