name: Excute migration command

on:
  push:
    branches:
      - test
      - test/*

jobs:
  migration:
    runs-on: ubuntu-latest
    env:
      RDB_URL: ${{ secrets.RDB_URL }}

    steps:
      - name: Test
        run: |
          MIGRATION_COMMAND=${GITHUB_REF#refs/heads/migration/}
          echo "MIGRATION_COMMAND=${MIGRATION_COMMAND}" >> $GITHUB_ENV
          echo "Repository Name: ${{ github.repository }}"
